// SPDX-License-Identifier: Apache-2.0
using Hiero.SDK.Cryptography;

using System.IO;

namespace Hiero.Tests.SDK.Keys
{
    /// <include file="tets-keys-keystore.cs.xml" path='docs/member[@name="T:Hiero.Tests.SDK.Keys.KeystoreTest"]' />
    public class KeystoreTest
    {
        private static readonly string TEST_KEY_STR = "302e020100300506032b657004220420db484b828e64b2d8f12ce3c0a0e93a0b8cce7af1bb8f39c97732394482538e10";
        private static readonly string PASSPHRASE = "asdf1234";
        [Fact]
        /// <include file="tets-keys-keystore.cs.xml" path='docs/member[@name="M:Hiero.Tests.SDK.Keys.KeystoreTest.KeystoreFromStream"]' />
        public virtual void KeystoreFromStream()
        {
            // keystore file generated by hedera-sdk-js from `testKeyStr` and `passphrase`
            // NOT USED ANYWHERE
            
            Keystore keystore = Keystore.FromStream(Resources.TestKeystore_Stream, PASSPHRASE);
            PrivateKey privateKey = keystore.GetEd25519();

            Assert.Equal(privateKey.ToString(), TEST_KEY_STR);
        }
        [Fact]
        /// <include file="tets-keys-keystore.cs.xml" path='docs/member[@name="M:Hiero.Tests.SDK.Keys.KeystoreTest.KeystoreFromStreamV2"]' />
        public virtual void KeystoreFromStreamV2()
        {
            // keystore file generated by hedera-sdk-js from `testKeyStr` and `passphrase`
            // NOT USED ANYWHERE
            Keystore keystore = Keystore.FromStream(Resources.TestKeystore2_Stream, PASSPHRASE);
            PrivateKey privateKey = keystore.GetEd25519();

            Assert.Equal(TEST_KEY_STR, privateKey.ToString());
        }
        [Fact]
        /// <include file="tets-keys-keystore.cs.xml" path='docs/member[@name="M:Hiero.Tests.SDK.Keys.KeystoreTest.KeystoreToStream"]' />
        public virtual void KeystoreToStream()
        {
            PrivateKey privateKey = PrivateKey.FromString(TEST_KEY_STR);
            Keystore keystore = new (privateKey);
            
			using MemoryStream outputStream = new (); 
            keystore.Export(outputStream, PASSPHRASE);
            using MemoryStream dataStream = new(outputStream.ToArray());

            // TODO Note: (MemoryStream or KeyStore.Export Issues?)
            // Keystore keystore2 = Keystore.FromStream(outputStream, PASSPHRASE); // Fails
            Keystore keystore2 = Keystore.FromStream(dataStream, PASSPHRASE); // Passes
            PrivateKey privateKey2 = keystore2.GetEd25519();

            Assert.Equal(TEST_KEY_STR, privateKey2.ToString());
        }
    }
}
